[package]
name = "pivot"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "pivot"
path = "src/cmd/pivot/main.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
structopt = "0.3"